# Generated by Django 2.1.5 on 2020-02-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0002_employeesheet_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesheet',
            old_name='Month',
            new_name='Month_calendar',
        ),
    ]
