# Generated by Django 2.1.5 on 2020-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0004_remove_employeesheet_month_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesheet',
            name='Month_calendar',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
