# Generated by Django 2.1.5 on 2020-02-19 12:42

import UploadApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0005_employeesheet_month_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesheet',
            name='sheet',
            field=models.FileField(blank=True, null=True, upload_to=UploadApp.models.directory_path),
        ),
    ]
