# Generated by Django 2.1.5 on 2020-02-26 10:33

import UploadApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0007_auto_20200220_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesheet',
            name='sheet',
            field=models.FileField(default=django.utils.timezone.now, upload_to=UploadApp.models.directory_path),
            preserve_default=False,
        ),
    ]
